apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml: 
    - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-393619
  artifacts:
    - image: eu.gcr.io/ticketing-dev-393619/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
